### ISSUE TITLE
[Not an issue] - Charging example

### ISSUE THREAD

**Issue by travisboss** [sbabcock23/hass-tryfi#68]
```yaml
- id: '1661129896868'
  alias: Pet's Collar - Fully Charged
  description: ''
  trigger:
    - platform: numeric_state
      entity_id: sensor.pet_collar_battery_level
      above: 99
  condition:
    - condition: state
      entity_id: binary_sensor.pet_collar_battery_charging
      state: 'on'
  action:
    - service: notify.everyone_phone
      data:
        message: "Pet's collar is fully charged!"
  mode: single
```

Might suggest updating to numeric state so anything over 99% is considered fully charged, can be a little cleaner.

**Comment by travisboss** [comment]
```yaml
- id: '1604060166498'
  alias: Turn on Light After Dark If Not Home
  description: ''
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: device_tracker.pet_tracker
      state: 'not_home'
  action:
    - service: light.turn_on
      target:
        entity_id: light.pet_collar_light
  mode: single
```

Here is an updated one for the light after dark example too, removing the and and simplifying the condition, going to `not_home` and `light.turn_on`
