### ISSUE TITLE
Change lost mode

### ISSUE THREAD

**Issue by ignacio82** [sbabcock23/hass-tryfi#71]
How can I change the lost mode with a service call? I tried this:

```
service: input_select.select_option
data:
  option: Lost
target:
  entity_id: select.maui_lost_mode
```
